name: XnnTransfer CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        config: [debug, release]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      # Install modern compiler on macOS AFTER xmake is installed
      - name: Install GCC on macOS
        if: runner.os == 'macOS'
        run: |
          brew install gcc@13
          echo "CC=$(brew --prefix gcc@13)/bin/gcc-13" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix gcc@13)/bin/g++-13" >> $GITHUB_ENV

      - name: Cache xmake packages
        uses: actions/cache@v4
        with:
          path: ~/.xmake/packages
          key: ${{ runner.os }}-${{ matrix.config }}-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.config }}-

      - name: Configure project
        run: xmake f -y -m ${{ matrix.config }}

      - name: Build XnnTransfer
        run: xmake build -y XnnTransfer

      - name: Build tests
        run: xmake build -y tests

      - name: Run tests
        run: xmake run tests